/*show all databases*/ 
show databases;

/* to use a database*/
USE postdb;

DROP TABLE IF EXISTS `post_test`;

CREATE TABLE `post_test` 
	(`POST_ID` BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, 
	`POST_TEXT` VARCHAR(1500) NOT NULL, 
	`POST_CREATED_TIME`	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`POST_CREATOR_TYPE` CHAR(25) NOT NULL,
	`ASSOCIATED_TONE`	CHAR(25),
	`ASSOCIATED_TONE_SCORE` CHAR(25)
	) AUTO_INCREMENT=1 ;
	
INSERT INTO `post_test` 
	(POST_TEXT, POST_CREATOR_TYPE, ASSOCIATED_TONE, ASSOCIATED_TONE_SCORE)
VALUES ('test from client', 'Member', 'Sad', '0.81258') ;

SELECT * FROM `post_test`;

DELETE FROM `post_test`;

DELETE FROM `post_test` WHERE `POST_ID` = 43;

